"""add lesson completed_at

Revision ID: 0000263594c0
Revises: a72c355080aa
Create Date: 2026-09-14 19:46:22.551622

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0000263594c0'
down_revision: Union[str, None] = 'a72c355080aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'completed_at')
    # ### end Alembic commands ###
